//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kindergarten2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PreSchoolEntities1 : DbContext
    {
        public PreSchoolEntities1()
            : base("name=PreSchoolEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tbl_address> tbl_address { get; set; }
        public virtual DbSet<tbl_attendance> tbl_attendance { get; set; }
        public virtual DbSet<tbl_child_healthy> tbl_child_healthy { get; set; }
        public virtual DbSet<tbl_child_info> tbl_child_info { get; set; }
        public virtual DbSet<tbl_disease_assignment> tbl_disease_assignment { get; set; }
        public virtual DbSet<tbl_disease_type> tbl_disease_type { get; set; }
        public virtual DbSet<tbl_employee> tbl_employee { get; set; }
        public virtual DbSet<tbl_food> tbl_food { get; set; }
        public virtual DbSet<tbl_nurse> tbl_nurse { get; set; }
        public virtual DbSet<tbl_room_name> tbl_room_name { get; set; }
        public virtual DbSet<tbl_rooms> tbl_rooms { get; set; }
        public virtual DbSet<tbl_sociologist> tbl_sociologist { get; set; }
        public virtual DbSet<tbl_subject_activity> tbl_subject_activity { get; set; }
        public virtual DbSet<tbl_time_table> tbl_time_table { get; set; }
        public virtual DbSet<tbl_user> tbl_user { get; set; }
    }
}
