//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kindergarten2
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_room_name
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_room_name()
        {
            this.tbl_rooms = new HashSet<tbl_rooms>();
            this.tbl_sociologist = new HashSet<tbl_sociologist>();
            this.tbl_subject_activity = new HashSet<tbl_subject_activity>();
        }
    
        public decimal id { get; set; }
        public string room_name { get; set; }
        public Nullable<decimal> id_user_save { get; set; }
        public Nullable<System.DateTime> datetime_save { get; set; }
        public Nullable<decimal> id_user_update { get; set; }
        public Nullable<System.DateTime> datetime_update { get; set; }
    
        public virtual tbl_user tbl_user { get; set; }
        public virtual tbl_user tbl_user1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_rooms> tbl_rooms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_sociologist> tbl_sociologist { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_subject_activity> tbl_subject_activity { get; set; }
    }
}
