//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kindergarten2
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_attendance
    {
        public decimal id { get; set; }
        public decimal id_child { get; set; }
        public System.TimeSpan time_income { get; set; }
        public Nullable<System.TimeSpan> time_left { get; set; }
        public string left_with { get; set; }
        public Nullable<decimal> id_user_save { get; set; }
        public Nullable<System.DateTime> date_save { get; set; }
    }
}
