//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kindergarten2
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_child_info
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_child_info()
        {
            this.tbl_nurse = new HashSet<tbl_nurse>();
            this.tbl_rooms = new HashSet<tbl_rooms>();
            this.tbl_sociologist = new HashSet<tbl_sociologist>();
        }
    
        public decimal id { get; set; }
        public string child_fullname { get; set; }
        public System.DateTime income_date { get; set; }
        public Nullable<decimal> id_user_save { get; set; }
        public System.DateTime datetime_save { get; set; }
        public Nullable<decimal> id_user_update { get; set; }
        public Nullable<System.DateTime> datetime_update { get; set; }
        public int form_number { get; set; }
        public System.DateTime child_birthday { get; set; }
        public string id_child_place_of_birth { get; set; }
        public string father_fullname { get; set; }
        public string father_phone { get; set; }
        public string mother_fullname { get; set; }
        public string mother_phone { get; set; }
        public string child_gender { get; set; }
        public string child_language { get; set; }
        public string child_nationality { get; set; }
        public string parent_email { get; set; }
        public string name_of_baby_steer { get; set; }
        public string baby_steer_phone { get; set; }
        public string id_child_address { get; set; }
        public string serial_of_child { get; set; }
        public string child_blood_type { get; set; }
        public Nullable<int> number_of_bro_and_sis { get; set; }
    
        public virtual tbl_user tbl_user { get; set; }
        public virtual tbl_user tbl_user1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_nurse> tbl_nurse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_rooms> tbl_rooms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_sociologist> tbl_sociologist { get; set; }
    }
}
