//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kindergarten2
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_food
    {
        public decimal id { get; set; }
        public string food_type { get; set; }
        public string weekday { get; set; }
        public string first_time { get; set; }
        public string second_time { get; set; }
        public string third_time { get; set; }
        public string forth_time { get; set; }
    }
}
